CREATE TABLE IF NOT EXISTS job(
	id UUID PRIMARY KEY,
	type VARCHAR(255) NOT NULL,
	payload JSONB NOT NULL,
	priority INTEGER NOT NULL,
	run_at TIMESTAMP WITH TIME ZONE,
	idempotency_key UUID,
	status VARCHAR(255) NOT NULL,
	attempts INTEGER NOT NULL,
	max_attempts INTEGER NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL
)
